package com.example.timer.others

object Constants {

    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_SHOW_TIMER_FRAGMENT = "ACTION_SHOW_TIMER_FRAGMENT"
    const val ACTION_PAUSE_BUTTON = "ACTION_PAUSE_BUTTON"
    const val ACTION_NEXT_BUTTON = "ACTION_NEXT_BUTTON"
    const val ACTION_PREVIEW_BUTTON = "ACTION_PREVIEW_BUTTON"
    const val NOTIFICATION_CHANNEL_ID = "tracking_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Tracking"
    const val NOTIFICATION_ID = 1
}